#!/usr/bin/env php
<?php

$loader = require __DIR__ . '/autoload.php';

use ConsoleSymfonyCommandsModule\ConsoleStore;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$app = new App(array('debug'=> $debug));
// Store App
ConsoleStore::store('app', $app);

$console = new Application('Silex Shop Catalog Application', '1.0');

foreach ($app->setModules() as $module) {
    $module->registerCommands($console);
}

$console->run($input);